# This workflow will build the website with pelican and publish (deploy) it to a webserver

name: Publish website

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: 'website'
      # will checkout the website repository as the default action

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pelican markdown

    - name: Checkout medvets-theme
      uses: actions/checkout@v2
      with:
        repository: 'medvets/medvets-theme'
        path: 'medvets-theme'
     
    - name: Checkout hierarchy plugin (from Samuels fork of pelican-plugins)
      uses: actions/checkout@v2
      with:
        repository: 'samueljohn/pelican-plugins'
        path: 'pelican-plugins'
        
    - name: Build website
      id: build
      run: |
        ls
        pelican -s website/pelicanconf.py -v -D 
        ls -la html/

    - name: Sync files to web server
      id: deploy
      uses: Burnett01/rsync-deployments@4.1
      # Generate like so:
      # ssh-keygen -f ~/.ssh/deploy_key_rsa -q -P "" 
      # cat ~/.ssh/deploy_key_rsa.pub
      # Add pub key to ~/.ssh/authorized_hosts
      # Add private deploy_key_rsa to Github as a secret on the website
      with:
        switches: -avzr --delete
        path: html/
        remote_path: /var/www/virtual/medvets/html/
        remote_host: vanness.uberspace.de
        remote_user: medvets
        remote_key: ${{ secrets.DEPLOY_KEY }}
        
